services:
  auuki-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped

  auuki-sync-backend:
    build: ./auuki-sync-backend
    ports:
      - "8000:8000"
    volumes:
      - ./.garmin_tokens:/data/garmin_tokens:Z
      - ./fit_files:/opt/data/fit_files
    environment:
      - GARMIN_TOKEN_STORE=/data/garmin_tokens
      - FIT_STORE_DIR=/opt/data/fit_files
    restart: unless-stopped
